# Generated by Django 4.2.4 on 2023-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano_lancamento', models.IntegerField()),
                ('Sinopse', models.CharField(max_length=200)),
            ],
        ),
    ]
