# Generated by Django 4.2.4 on 2023-08-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_filmes', '0002_rename_titulo_filme_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='id',
            new_name='id_filme',
        ),
        migrations.AlterField(
            model_name='filme',
            name='Sinopse',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='filme',
            name='nome',
            field=models.TextField(max_length=100),
        ),
    ]
