# Generated by Django 4.2.4 on 2023-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_filmes', '0003_rename_id_filme_id_filme_alter_filme_sinopse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id_filme', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano_lancamento', models.IntegerField()),
                ('Sinopse', models.TextField(max_length=250)),
                ('capa', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
    ]
