# Generated by Django 4.2.4 on 2023-08-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_filmes', '0004_filmes_delete_filme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filmes',
            new_name='Filme',
        ),
    ]
